<?php // Social Links
$html = $this->getSocialLinks();
echo '<ul class="social-links">';
?>
     <li><a target="_blank" class="" href="https://twitter.com/amberbuddyau" >
		<img src="https://www.amberbuddy.com.au/social/t.png" alt="Twitter" title="Twitter">
	 </a>
			
			</li>
	 <li><a target="_blank" class="" href="https://instagram.com/amberbuddyau">
		<img src="https://www.amberbuddy.com.au/social/i.png" alt="Instagram" title="Instagram">
	 </a>
	 
	 </li>
	 <li><a target="_blank" class="" href="https://facebook.com/amberbuddyau">
		<img src="https://www.amberbuddy.com.au/social/f.png" alt="Facebook" title="Facebook">
	 </a></li>
	 <li><a target="_blank" class="" href="https://plus.google.com/u/1/113420870238585042473/posts">
		<img src="https://www.amberbuddy.com.au/social/g.png" alt="Google+" title="Google+">
	 </a></li>
	 <li><a target="_blank" class="" href="https://www.pinterest.com/AmberBuddyAU">
		<img src="https://www.amberbuddy.com.au/social/p.png" alt="Pinterest" title="Pinterest">
	 </a></li>
        
		<?php
echo '</ul>';
?>